import { DeliveryOption, Product, PromoCode } from './storefront.models';

export const STORE_NAME = 'Atelier South';
export const CURRENCY_CODE = 'AUD';
export const SUPPORT_EMAIL = 'concierge@ateliersouth.co';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'meridian-trench',
    name: 'Meridian Trench',
    category: 'Outerwear',
    collection: 'City Line',
    price: 340,
    originalPrice: 390,
    description: 'A fluid trench with a cinched waist and a brushed cotton finish that moves from office mornings to harbor nights.',
    story: 'Cut with a sculpted shoulder and a softened drape, the Meridian layers easily over tailoring without feeling rigid.',
    fit: 'Relaxed through the body with a removable belt and room for lightweight layers underneath.',
    fabric: 'Water-resistant cotton twill lined with a breathable satin back.',
    highlights: ['Storm flap with hidden snap closure', 'Deep welt pockets and internal phone sleeve', 'Split hem for easier movement on the go'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Shell', swatch: '#d7c7b7' },
      { name: 'Ink', swatch: '#1b2230' },
    ],
    palette: ['#f5ece0', '#b7977c', '#283047'],
    silhouette: 'coat',
    badge: 'Best Seller',
  },
  {
    id: 2,
    slug: 'harbor-wool-coat',
    name: 'Harbor Wool Coat',
    category: 'Outerwear',
    collection: 'Evening Layer',
    price: 460,
    description: 'A full-length wrap coat designed to sit cleanly over dresses and soft knits.',
    story: 'The Harbor coat balances structure and softness with a generous shawl collar and a quiet, luxurious hand feel.',
    fit: 'Longline shape with a dropped shoulder and tailored waist seam.',
    fabric: 'Double-faced wool blend with bound seams and a cashmere-soft brushed surface.',
    highlights: ['Fully lined sleeves for smooth layering', 'Detachable belt with horn-tone hardware', 'Back vent for easy stride'],
    sizes: ['S', 'M', 'L'],
    colors: [
      { name: 'Moss', swatch: '#626655' },
      { name: 'Noir', swatch: '#24252a' },
    ],
    palette: ['#eeeadf', '#84856d', '#2b2c35'],
    silhouette: 'coat',
    badge: 'New Season',
  },
  {
    id: 3,
    slug: 'afterglow-knit-polo',
    name: 'Afterglow Knit Polo',
    category: 'Knitwear',
    collection: 'Soft Structure',
    price: 148,
    description: 'A ribbed knit polo with an open placket and easy drape for polished off-duty styling.',
    story: 'Designed to sit between a tee and a cardigan, the Afterglow adds softness without losing shape.',
    fit: 'Slim fit with stretch through the body and a cropped hem that pairs with high-rise trousers.',
    fabric: 'Fine merino-cotton blend with compact rib construction.',
    highlights: ['Milano stitched collar', 'Clean tubular hem and sleeve finish', 'Naturally breathable with light warmth'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Bone', swatch: '#e7ddd0' },
      { name: 'Garnet', swatch: '#77373d' },
    ],
    palette: ['#f8f1e8', '#bc8d71', '#6f3643'],
    silhouette: 'knit',
  },
  {
    id: 4,
    slug: 'solace-cashmere-cardigan',
    name: 'Solace Cashmere Cardigan',
    category: 'Knitwear',
    collection: 'After Hours',
    price: 220,
    description: 'A featherweight cardigan with a deep V and tonal buttons for layering across seasons.',
    story: 'The Solace cardigan is designed as a quiet luxury layer with a deliberately fluid neckline.',
    fit: 'Softly fitted with extra length through the sleeve and torso.',
    fabric: 'Pure cashmere spun to a light 12-gauge knit.',
    highlights: ['Fully fashioned shoulder', 'Tone-on-tone corozo buttons', 'Easy tuck front hem'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Cloud', swatch: '#d8d5d1' },
      { name: 'Espresso', swatch: '#5c433c' },
    ],
    palette: ['#f7f4f0', '#b9aca5', '#54403c'],
    silhouette: 'knit',
    badge: 'Limited Run',
  },
  {
    id: 5,
    slug: 'coastline-pleat-dress',
    name: 'Coastline Pleat Dress',
    category: 'Dresses',
    collection: 'Resort Edit',
    price: 228,
    description: 'A pleated midi dress with a sweeping skirt and a softly draped neckline.',
    story: 'The Coastline dress was built for movement, with engineered pleats that keep their shape from afternoon light to dinner.',
    fit: 'Slim through the waist with a fluid midi-length skirt and adjustable straps.',
    fabric: 'Recycled satin twill with heat-set pleating and matte lining.',
    highlights: ['Invisible side zip and full lining', 'Adjustable straps for a better neckline fit', 'Designed to pack without losing shape'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Blush Sand', swatch: '#d0b7a4' },
      { name: 'Sea Ink', swatch: '#2a3f53' },
    ],
    palette: ['#f9f1e8', '#ca9a7d', '#355067'],
    silhouette: 'dress',
    badge: 'Travel Favorite',
  },
  {
    id: 6,
    slug: 'nocturne-slip-dress',
    name: 'Nocturne Slip Dress',
    category: 'Dresses',
    collection: 'Studio Evening',
    price: 198,
    description: 'A bias-cut slip dress with a minimalist neckline and luminous sheen.',
    story: 'Nocturne is cut to skim the body without clinging, giving evening dressing a quieter confidence.',
    fit: 'Bias silhouette with a smooth hip line and midi hem.',
    fabric: 'Silk-touch acetate blend with fluid drape and soft luster.',
    highlights: ['Internal bust binding for shape', 'Adjustable rouleau straps', 'Cut on the bias for fluid movement'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Bronze', swatch: '#7f5a4f' },
      { name: 'Moonstone', swatch: '#c1c1c7' },
    ],
    palette: ['#fbf3ec', '#9a6d58', '#7d7d90'],
    silhouette: 'dress',
  },
  {
    id: 7,
    slug: 'frame-wool-blazer',
    name: 'Frame Wool Blazer',
    category: 'Tailoring',
    collection: 'Soft Tailoring',
    price: 310,
    description: 'A relaxed single-breasted blazer that sharpens denim, silk skirts, and matching trousers alike.',
    story: 'Frame combines a softened shoulder with precise pocket placement to keep tailoring refined rather than stiff.',
    fit: 'Straight fit with gentle waist shaping and a longer line through the hip.',
    fabric: 'Italian wool suiting with a touch of stretch and smooth sleeve lining.',
    highlights: ['Functional cuff vents', 'Hidden internal ticket pocket', 'Light shoulder pad for clean drape'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Stone', swatch: '#bdb1a5' },
      { name: 'Navy', swatch: '#24324a' },
    ],
    palette: ['#f4efe9', '#c6ab95', '#23324d'],
    silhouette: 'tailoring',
    badge: 'Editor Pick',
  },
  {
    id: 8,
    slug: 'daybreak-wide-leg-trouser',
    name: 'Daybreak Wide-Leg Trouser',
    category: 'Tailoring',
    collection: 'Soft Tailoring',
    price: 185,
    description: 'A draped trouser with a clean front and full-length leg for an elongated line.',
    story: 'The Daybreak trouser is designed to pool slightly over sandals or a low heel, bringing softness to tailoring.',
    fit: 'High-rise fit with a long wide leg and internal waist tab.',
    fabric: 'Fluid crepe suiting with a soft matte finish.',
    highlights: ['Tailor-friendly hem allowance', 'Angled slash pockets', 'Elastic comfort panel at back waist'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Sandstone', swatch: '#c5b39f' },
      { name: 'Graphite', swatch: '#454d57' },
    ],
    palette: ['#fbf4ea', '#c59c7b', '#47525f'],
    silhouette: 'tailoring',
  },
  {
    id: 9,
    slug: 'studio-rib-tank',
    name: 'Studio Rib Tank',
    category: 'Essentials',
    collection: 'Foundation',
    price: 74,
    description: 'A finely ribbed tank with a sculpted neckline that anchors any layered look.',
    story: 'Studio is the foundational piece in the wardrobe edit, balancing stretch recovery with a clean, premium hand feel.',
    fit: 'Close fit with a subtly curved armhole and full-length body.',
    fabric: 'Compact organic cotton rib with a touch of elastane.',
    highlights: ['Self-bound neckline', 'Double-needle hem', 'Layer-friendly weight'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Ivory', swatch: '#f2eee8' },
      { name: 'Pebble', swatch: '#8a8077' },
    ],
    palette: ['#fff8f2', '#cdc0b0', '#7d7670'],
    silhouette: 'essentials',
  },
  {
    id: 10,
    slug: 'arcade-poplin-shirt',
    name: 'Arcade Poplin Shirt',
    category: 'Essentials',
    collection: 'Foundation',
    price: 132,
    description: 'An oversized poplin shirt with a crisp collar and a longer back hem.',
    story: 'Arcade is cut with an ease that feels borrowed but still precise, making it the fastest way to polish a look.',
    fit: 'Oversized through the body with a neat collar and tapered cuff.',
    fabric: 'Crisp stretch cotton poplin with a washed finish.',
    highlights: ['Dropped shoulder and curved hem', 'Mother-of-pearl style buttons', 'Convertible cuff for casual rolling'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'White', swatch: '#f7f5f2' },
      { name: 'Sky', swatch: '#b6cad7' },
    ],
    palette: ['#fcfbf8', '#d9d0c8', '#b1c6d4'],
    silhouette: 'essentials',
  },
];

export const PROMO_CODES: PromoCode[] = [
  {
    code: 'FIRSTLOOK',
    label: '10% off your first order over A$200',
    type: 'percentage',
    value: 0.1,
    minimumSubtotal: 200,
  },
  {
    code: 'SETMATCH',
    label: 'A$35 off complete looks over A$320',
    type: 'fixed',
    value: 35,
    minimumSubtotal: 320,
  },
];

export const DELIVERY_OPTIONS: DeliveryOption[] = [
  {
    id: 'studio-standard',
    label: 'Studio Standard',
    description: 'Tracked delivery with signature concierge packaging.',
    eta: '3-5 business days',
    price: 18,
  },
  {
    id: 'express-dispatch',
    label: 'Express Dispatch',
    description: 'Priority packing and faster metro delivery windows.',
    eta: '1-2 business days',
    price: 28,
  },
  {
    id: 'boutique-pickup',
    label: 'Boutique Pickup',
    description: 'Reserve online and collect from the Sydney flagship.',
    eta: 'Ready tomorrow after 10 AM',
    price: 0,
  },
];

export const EDITORIAL_PANELS = [
  {
    title: 'Layered for the in-between season',
    body: 'Tailoring that feels light, dresses that move, and outerwear cut for early-evening breeze.',
  },
  {
    title: 'Built to mix, not just match',
    body: 'Each piece is designed to sit across the edit, so one cart turns into several looks without feeling repetitive.',
  },
  {
    title: 'Concierge details, already included',
    body: 'Complimentary hemming notes, premium garment care cards, and easy 30-day returns come standard.',
  },
];

export const PRODUCT_CATEGORIES = [...new Set(PRODUCTS.map((product) => product.category))];

export function getProductBySlug(slug: string | null | undefined): Product | undefined {
  return PRODUCTS.find((product) => product.slug === slug);
}
